// AUTO-GENERATED by build.rs from protocol_lambda.toml
// DO NOT EDIT — edit protocol_lambda.toml instead.

pub const CONSOLE_COOLDOWN_TICKS: u64 = 1555200;
pub const CONSOLE_VOTING_WINDOW_TICKS: u64 = 17280;
pub const CONSOLE_LIVENESS_INTERVAL_TICKS: u64 = 1555200;
pub const CONSOLE_LIVENESS_RESPONSE_TICKS: u64 = 51840;
pub const DWP_EXPIRY_SECS: u64 = 31536000;
pub const JFP_FREEZE_DURATION_SECS: u64 = 31536000;
