// AUTO-GENERATED by build.rs from protocol_lambda.toml
// DO NOT EDIT — edit protocol_lambda.toml instead.

#[cfg(not(feature = "dev-tuning"))]
pub const CONSOLE_COOLDOWN_TICKS: u64 = 1555200;
#[cfg(feature = "dev-tuning")]
pub const CONSOLE_COOLDOWN_TICKS: u64 = 24;
#[cfg(not(feature = "dev-tuning"))]
pub const CONSOLE_VOTING_WINDOW_TICKS: u64 = 518400;
#[cfg(feature = "dev-tuning")]
pub const CONSOLE_VOTING_WINDOW_TICKS: u64 = 60;
#[cfg(not(feature = "dev-tuning"))]
pub const CONSOLE_MEMBER_VOTE_TICKS: u64 = 17280;
#[cfg(feature = "dev-tuning")]
pub const CONSOLE_MEMBER_VOTE_TICKS: u64 = 24;
#[cfg(not(feature = "dev-tuning"))]
pub const CONSOLE_LIVENESS_INTERVAL_TICKS: u64 = 1555200;
#[cfg(feature = "dev-tuning")]
pub const CONSOLE_LIVENESS_INTERVAL_TICKS: u64 = 60;
#[cfg(not(feature = "dev-tuning"))]
pub const CONSOLE_LIVENESS_RESPONSE_TICKS: u64 = 51840;
#[cfg(feature = "dev-tuning")]
pub const CONSOLE_LIVENESS_RESPONSE_TICKS: u64 = 24;
pub const DWP_EXPIRY_SECS: u64 = 31536000;
pub const JFP_FREEZE_DURATION_SECS: u64 = 31536000;
pub const MAX_FACT_LINKS: u64 = 16;
#[cfg(not(feature = "dev-tuning"))]
pub const VBC_SIGNS_BUDGET: u64 = 6;
#[cfg(feature = "dev-tuning")]
pub const VBC_SIGNS_BUDGET: u64 = 100;
pub const PULSE_CANDIDACY_MAX_ENTRIES: u64 = 1024;
#[cfg(not(feature = "dev-tuning"))]
pub const PULSE_CANDIDACY_MIN_REQUEST_INTERVAL_TICKS: u64 = 720;
#[cfg(feature = "dev-tuning")]
pub const PULSE_CANDIDACY_MIN_REQUEST_INTERVAL_TICKS: u64 = 30;
pub const IDEMPOTENCY_CACHE_BYTES: u64 = 67108864;
pub const ATTESTED_TICK_FUTURE_SKEW_SECS: u64 = 300;
