// AXIOM Lambda — Build Script
//
// Reads protocol_lambda.toml and generates src/tuning_gen.rs with compile-time
// constants. Mirrors core/logic/build.rs: a `foo` + `foo_dev` PAIR emits ONE
// constant under the base name, selected by the `dev-mode` feature. A standalone
// key (no `_dev` pair) emits a single always-on constant. No external deps.
use std::fs;
use std::path::Path;

fn main() {
    let conf_path = Path::new("protocol_lambda.toml");
    println!("cargo:rerun-if-changed=protocol_lambda.toml");

    let content = fs::read_to_string(conf_path)
        .unwrap_or_else(|e| panic!("Cannot read protocol_lambda.toml: {}", e));

    // Pass 1: collect KEY = VALUE entries (skip blanks / # comments / [sections]).
    let mut entries: Vec<(String, String)> = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim().to_string();
            // Strip inline comment + underscore separators: "31_536_000  # 1yr" → "31536000".
            let value = value.split('#').next().unwrap_or("").trim().replace('_', "");
            entries.push((key, value));
        }
    }

    // Pass 2: emit, honoring the `_dev`-pair convention.
    let has = |name: &str| entries.iter().any(|(k, _)| k == name);
    let mut out = String::from(
        "// AUTO-GENERATED by build.rs from protocol_lambda.toml\n// DO NOT EDIT — edit protocol_lambda.toml instead.\n\n",
    );
    for (key, value) in &entries {
        if let Some(base) = key.strip_suffix("_dev") {
            if has(base) {
                out.push_str(&format!(
                    "#[cfg(feature = \"dev-mode\")]\npub const {}: u64 = {};\n",
                    base.to_uppercase(),
                    value
                ));
                continue;
            }
        }
        if has(&format!("{key}_dev")) {
            out.push_str(&format!(
                "#[cfg(not(feature = \"dev-mode\"))]\npub const {}: u64 = {};\n",
                key.to_uppercase(),
                value
            ));
            continue;
        }
        out.push_str(&format!("pub const {}: u64 = {};\n", key.to_uppercase(), value));
    }

    fs::write(Path::new("src/tuning_gen.rs"), out)
        .unwrap_or_else(|e| panic!("Cannot write src/tuning_gen.rs: {}", e));
}
